version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
  ignore:
  - dependency-name: System.Drawing.Common
    versions:
    - 5.0.0
- package-ecosystem: nuget
  directory: "/tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
- package-ecosystem: nuget
  directory: "/tools/packaging/projects/reference/System.Management.Automation"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
- package-ecosystem: nuget
  directory: "/test/tools/Modules"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
- package-ecosystem: nuget
  directory: "/src/Modules"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
